# Build docker image based of the artifact created by `mvn package`
FROM eclipse-temurin:21-alpine

RUN apk add --no-cache curl jq bash coreutils

ADD target/tibber-meter-uploader-1.0.0-SNAPSHOT.jar /tibber-meter-uploader.jar

CMD /tibber-meter-uploader.jar
